import type { Metadata } from "next";
import { Montserrat_Alternates } from "next/font/google";
import "./globals.css";

const montAlt = Montserrat_Alternates({
  weight: "400",
  variable: "--font-russo-one",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Todo List ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montAlt.variable} antialiased`}
        style={{ fontFamily: montAlt.style.fontFamily }}
      >
        {children}
      </body>
    </html>
  );
}
